{% set name = "dive" %}
{% set version = "0.12.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/wagoodman/dive/archive/v{{ version }}.tar.gz
    sha256: 2b69b8d28220c66e2575a782a370a0c05077936ae3ce69180525412fcca09230
  - url: https://raw.githubusercontent.com/logrusorgru/aurora/304bc2c7ed50ec832069fe4a88f35c4bc128eb45/LICENSE
    sha256: 7e12e5df4bae12cb21581ba157ced20e1986a0508dd10d0e8a4ab9a4cf94e85c
    fn: LICENSE-aurora

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - dive --help

about:
  home: https://github.com/wagoodman/dive
  license: MIT
  license_file:
    - LICENSE
    - LICENSE-aurora
    - license-files/
  summary: A tool for exploring a docker image, layer contents, and discovering ways to shrink the size of your Docker/OCI image.

extra:
  recipe-maintainers:
    - xhochy
